
### Get all contacts
GET http://cse341-vcsw.onrender.com/contacts


### Get contact by id
GET http://cse341-vcsw.onrender.com/contacts/67d79fbbfb1ad26c88baeae5


### Create contact
POST http://cse341-vcsw.onrender.com/contacts
Content-Type: application/json

{
"firstName": "John",
"lastName": "Doe",
"email": "johndoe@example.com",
"favoriteColor": "Green",
"birthday": "1990-05-15"
}

###Update a contact
PUT http://cse341-vcsw.onrender.com/contacts/67d79fbbfb1ad26c88baeaee
Content-Type: application/json

{
"firstName": "Daniel",
"lastName": "Johnson",
"email": "daniel@johnson.com",
"favoriteColor": "Green",
"birthday": "1990-05-15"
}

###Delete a contact
DELETE http://cse341-vcsw.onrender.com/contacts/67d7a8b885a39f45d5a5721a